logintest/login_signup/urls.py
from django.conf.urls import url
from login_signup import views
from django.urls import path,re_path
app_name = 'login_signup'
urlpatterns=[
    path('',views.signup),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate , name='activate'),

]

logintest/logintest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login_signup import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.main,name='main'),
    #url(r'^special/',views.special,name='special'),
    url(r'^login_signup/',include('login_signup.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

logintest/login_signup/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE)
def __str__(self):
  return self.user.username

class UserData(models.Model):
    email = models.EmailField(max_length=200, help_text='Required')
    name = models.CharField(max_length=200)
    password= models.CharField(max_length=200)

logintest/login_signup/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta():
        model = User
        fields = ('username','password','email')

logintest/login_signup/views.py
from django.shortcuts import render,redirect
from login_signup.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .models import UserData
import requests

#from django.contrib.auth.decorators import login_required


def main(request):
    return render(request,'login_signup/main.html')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('main'))
def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active=False
            user.set_password(user.password)
            user.save()
            registered = True
            current_site = get_current_site(request)
            domain=current_site.domain
            print(domain)
            message = render_to_string('acc_active_email.html', {
                'user':user,
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            name= user_form.cleaned_data.get('username')
            password=user_form.cleaned_data.get('password')
            print(name)
            print(password)
            response = requests.get("http://api.quickemailverification.com/v1/verify?email="+to_email+"&apikey=519847e067dab09cd0a1c56e334105fffa8dd9793a96ccc61c808db1ae7f")
            result=response.json()

            if (result['did_you_mean']=='' and result['result']=="valid"):
                print("valid")
                userdata=UserData.objects.create(email=to_email,name=name,password=password)
                userdata.save()
                mail_subject = 'Activate your blog account.'
                to_email = user_form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                return HttpResponse("Please click on the link sent to your mail to activate your account")

            else:
                try:
                    u=User.objects.get(username=name)
                    u.delete()
                except User.DoesNotExist:
                    return HttpResponse('The email given is invalid please check it ')
                except Exception as e:
                    return render(request,'login_signup/signup.html',{'user_form':user_form})
                return HttpResponse('The email given is invalid please check it ')


        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request,'login_signup/signup.html',{'user_form':user_form,'registered':registered})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        # return redirect('home')
        return render(request,'login_signup/login.html',{})
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        # return render(request, 'login.html', {'form': form})
    else:
        return HttpResponse('Activation link is invalid!')



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('main'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login_signup/login.html', {})

logintest/login_signup/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'login_signup:activate' uidb64=uid token=token %}
{% endautoescape %}

logintest/login_signup/templates/login_signup/login.html
<!DOCTYPE html>
<html>
<head>
<style>
form {
    border: 3px solid black;
}
body{
color:teal;
}
input[type="text"], input[type="password"] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid black;
    box-sizing: border-box;
    color:white;
    }
input[type="text"],input[type="password"],textarea{
        background-color:#5F6367;
        opacity:0.1;
        color:white;
}
button:hover {
    opacity: 0.5;
}
.cancelbtn {
    border: none;
    margin: 8px 0;
    width: auto;
    padding: 15px 30px;
    color: white;
    background-color: teal;
}
@media screen and (max-width: 300px) {
    span.psw {
        display: block;
        float: none;
    }
    .cancelbtn {
        width: 100%;
    }
}
.modal-content {
    padding-left:20px;
    padding-right:20px;
    padding-bottom: 20px;
    background-color:rgba(0,0,0,0.9);
    opacity =0.6;
    margin: 5px auto;
    border: 1px solid black;
    width: 18%;
}
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}
@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}
@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}
</style>
</head>
<body>
<b>
<br><br><br><br><br><br><br><br>
<form method="post" class="modal-content animate " font-size="20px"; action="{% url 'login_signup:user_login' %}"   >
  <br>
{% csrf_token %}
{{ user_form.as_p }}
  <center><h2>Login</h2></center>
  <br for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
  <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
  <div >
  <br>
      <center>
      <button type="button" onclick= location.href="{% url 'main' %}" class="cancelbtn">Cancel</button>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <button type="submit"  class="cancelbtn" >Login</button>
      </center>
    </div>
</form>
</b>
</body>
</html>

logintest/login_signup/templates/login_signup/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
     <style>
button {
    background-color: teal;
    color: white;
    padding: 1px 2px;
    margin: 5px 0;
    border: none;
    cursor: pointer;
    width: 10%;
}
button:hover {
    opacity: 0.8;
}
</style>
  </head>
  <body>
{% if user.is_authenticated %}
  <p><button onclick=location.href="{% url 'logout' %}" ><h4>logout</h4></button></p>
{% else %}
  <button onclick=location.href="{% url 'login_signup:user_login' %}"><h4>Login</h4></button>
  <button onclick=location.href="{% url 'login_signup:signup' %}" ><h4>Signup</h4></button>
{% endif %}
  </body>
</html>

logintest/login_signup/templates/login_signup/signup.html
<!DOCTYPE html>
<html>
<head>
<style>
body{
color:teal;
}
input[type="text"], input[type="password"],input[type="email"]{
    color:teal;
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid black;
    box-sizing: border-box;
    }
input[type="text"],input[type="password"],input[type="email"],textarea{
        background-color:#3d3d29;
        opacity:0.1;
        color:white;
}
button {
  background-color: teal;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 40%;
  opacity: 0.9;
}
button:hover {
  opacity:0.7;
}
.container {
  padding: 16px;
}
.modal-content {
  background-color:rgba(0,0,0,0.9);
  margin: 5% auto 15% auto;
  border: 1px solid teal;
  width: 30%;
}
hr {
  border: 1px solid teal;
  margin-bottom: 25px;
}
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}
@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}
@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}
</style>
</head>
<body>
  <form method="post" class="modal-content animate" action="{% url 'login_signup:signup' %}">
    <div class="container">
    <center><h2>Signup</h2></center>
    {% csrf_token %}
    {{ user_form.as_p }}
    <div class="clearfix">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="button" onclick=location.href="{% url 'main' %}"  class="cancelbtn">Cancel</button>
        &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;
        <button type="submit" onsubmit=location.href="{% url 'main' %} ">Sign Up</button>

      </div>
    </div>
  </form>
</body>
</html>